name: torch-quan
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.8.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.8
  - numpy
  - scikit-learn
  - matplotlib
  - jupyterlab
  - onnx
  - onnxruntime
  - torchserve
  - torch-model-archiver
  - tqdm
  - pillow
  - py-cpuinfo
